{{- if .Values.mesh.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "starter-kit.fullname" . }}-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - hosts:
    - "*"
    port:
      number: 80
      name: http
      protocol: HTTP
{{- end}}