{{- if .Values.mesh.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "starter-kit.fullname" . }}-virtualservice
spec:
  hosts:
  - "*"
  gateways:
  - {{ include "starter-kit.fullname" . }}-gateway
  http:
  - match:
    - uri:
        exact: /health
    route:
    - destination:
        host: {{ include "starter-kit.fullname" . }}
        port:
          number: {{ .Values.service.port }}  
  - match:
    - uri:
        exact: /ui
    route:
    - destination:
        host: {{ include "starter-kit.fullname" . }}
        port:
          number: {{ .Values.service.port }}                
{{- end}}        